title: 在任何 Linux 发行版中使用 Deepin Wine WeChat
date: 2021-07-22 23:34
desc: 从咱喵把系统换成 openSUSE 以来一直都没有找到在这个系统上像在 Arch 上一样使用 Deepin Wine 微信的体验。咱尝试了各种版本的微信，好像没有一个是满意的。所以自己倒腾出了一个能在任意发行版上用 Deepin Wine 运行最新微信的方法。
