title: 凌莞的 Arch Linux 安装笔记
desc: 我从第一次用上 Arch Linux 开始大概有一年多了，在这段时间里我大概也装了十几台 Arch Linux 的设备吧，台式机 笔记本 服务器 ChromeBook 都有。所以我今天想说一下我自己安装 Arch Linux 的方法
banner: https://cdn.lwqwq.com/pic/202203010000097.webp
date: 2022-03-01
